services:
  web:
    build: .
    volumes:
      - .:/myapp
    ports:
      - "3001:80"
    depends_on:
      - db
  db:
    platform: linux/x86_64
    image: mysql:8.0.27
    container_name: app_db
  mysql:
    image: mysql:8.0.27
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: shopping-cart-db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=mysql
    ports:
      - "8080:80"
volumes:
  db-data: